#------ spring ÅäÖÃ ------
spring:
  application:
    name: eureka-server
  profiles: eureka-server1

#------ web ÈİÆ÷ ------
server:
  port: 8000

#------ ×¢²áÖĞĞÄÅäÖÃ ------
eureka:
  instance:
    hostname: eureka-server1
  client:
    service-url:
      defaultZone: http://eureka-server2:8001/eureka/

---

#------ spring ÅäÖÃ ------
spring:
  application:
    name: eureka-server
  profiles: eureka-server2

#------ web ÈİÆ÷ ------
server:
  port: 8001

#------ ×¢²áÖĞĞÄÅäÖÃ ------
eureka:
  instance:
    hostname: eureka-server2
  client:
    service-url:
      defaultZone: http://eureka-server1:8000/eureka/
